language: scala
scala:
  - 2.12.2
jdk:
  - oraclejdk8

test:
  - sbt ++$TRAVIS_SCALA_VERSION test
before_deploy:
  - sbt universal:packageBin universal:packageZipTarball
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  skip_cleanup: true
  file:
    - server/target/universal/*.tgz
    - server/target/universal/*.zip
  on:
    tags: true